site_name: PCCF FPB Informàtica
site_description: Plantilla per a la creació de continguts del cicle formatiu de
  formació professional bàsica d'informàtica del IES Jaume el Just
site_author: JB Talens
site_url: https://juatafe.github.io/PCCF-FPB-Inform-tica/
use_directory_urls: false
docs_dir: 'md-docs'
site_dir: 'docs'

theme:
  name: material
  logo: "assets/img/logos/logoJust.png"
  favicon: "assets/img/logos/logo50.ico"
  language: ca
  features:
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
  palette: 
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Mode oscur
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Mode clar

extra:
  logo: |
    <div class="md-logo-container">
      <a href="https://portal.edu.gva.es/iesjaumeeljust/" target="_blank" class="logo-just"></a>
      <a href="https://ceice.gva.es/va/web/educacion" target="_blank" class="logo-gvanext"></a>
    </div>
  social:
    - icon: material/email
      link: mailto:jb.talensfelis@edu.gva.es
      name: Contacte
  consent:
    title: Consentiment de Cookies
    description: Utilitzem cookies per reconèixer les vostres visites i preferències repetides, així com per mesurar l'eficàcia de la nostra documentació i si els usuaris troben el que estan cercant. Amb el vostre consentiment, ens esteu ajudant a millorar la nostra documentació.
  generator: false

copyright: |
  <div class="custom-footer">
    <div class="footer-logo footer-left"></div>
    <span class="footer-text">© 2025 Llicència CC BY-NC-SA 4.0</span>
    <div class="footer-logo footer-right"></div>
  </div>

nav:
  - Introducció: 1-Introduccio.md
  - Marc normatiu: 2-MarcNormatiu.md
  - Adequació de les competències: 3-Adequacio.md
  - Contribucio a les competències: 4-Contribucio-Compet.md
  - Contribucio a la Ocupabilitat: 5-Contribucio-Ocupa.md
  - Enfocaments metodològics: 6-EnfocamentsDidactics.md
  - Organització dels mòduls: 7-OrganitzacioModuls.md
  - Criteris generals: 8-CriterisGenerals.md
  - Bases de dades d'empreses: 9-BasesDades.md
  - Criteris plans formatius: 10-CriterisPlans.md
  - Criteris Digitalització i Sostenibilitat: 11-CriterisDigiSos.md
  - Pla Tutorial: 12-PlaTutorial.md
  - Correcció dels plans i els programes: 13-CorreccioPlans.md
  - Orientció per a l'ús dels espais: 14-OrientacioUsEspais.md
  - Criteris d'avaluació: 15-CriterisAva.md
  - Mesures de resposta educativa a la inclusió: 16-MRI.md
  - Criteris per a la planificació d'activitats: 17-CriterisActivitats.md
  - Criteris per a la planificació de projectes: 18-CriterisModulP.md
  - Altres aspectes: 19-Altres.md
  - Programacions d'aula: 20-PA.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - assets/stylesheets/extracsspdf.css
  - assets/stylesheets/customs.css
  - assets/stylesheets/extra.css

plugins:
  - search
  - social:
      cards_layout_options:
        background_image: "assets/img/fondo.png"
        background_color: "#0FF1CE8F"
        text_color: "#000000"
        button_color: "#000000"
        button_text_color: "#FFFFFF"
        button_text: "Més informació"
